name: Deploy from Issue

on:
  issues:
    types: [opened, edited]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch Issue Details
        run: |
          ISSUE_URL="${{ github.event.issue.url }}"
          echo "Fetching issue body from: ${ISSUE_URL}"
          ISSUE_BODY=$(curl -s -H "Accept: application/vnd.github.v3+json" ${ISSUE_URL} | jq -r '.body')
          
          # Debug: Output the raw issue body
          echo "Raw issue body:"
          echo "${ISSUE_BODY}"

      - name: Extract branch name
        run: |
          ISSUE_URL="${{ github.event.issue.url }}"
          ISSUE_BODY=$(curl -s -H "Accept: application/vnd.github.v3+json" ${ISSUE_URL} | jq -r '.body')

          # Extract the branch name from the issue body
          BRANCH_NAME=$(echo "${ISSUE_BODY}" | sed -n '/### BRANCH/{n;p;}' | xargs)

          echo "Extracted Branch Name: ${BRANCH_NAME}"

          # Fail if no branch name is found
          if [ -z "$BRANCH_NAME" ]; then
            echo "Error: Branch name not found in the issue body."
            exit 1
          fi
          
          # Set the extracted branch name as a GitHub environment variable
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV

      - name: Checkout to the specified branch
        run: |
          echo "Checking out branch: ${{ env.BRANCH_NAME }}"
          git checkout ${{ env.BRANCH_NAME }}

      - name: Build project
        run: ./gradle.bootjar
